# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 1caeb447eb6902a2e43f8427a667fe9541d187a72a602609f0d7759d9e89f4ae3141418b5bb51eeb7e7ceed8be6d64c985bb6420eecc50eb0845a7c938c0ea36

test:
  domain_name: example.com 
  secret_key_base: 672b568190a01e50795d3881e606501925e646bb25cf52ce5aa53da64b9810b589185deff0361a56330e34b3556cfcf3478c70e1b34d8f9866f932c958a9b11d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
